name: methylcdm-env
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4=pyhd8ed1ab_1
  - asttokens=3.0.1=pyhd8ed1ab_0
  - blas=1.0=openblas
  - bottleneck=1.4.2=py311h03d0aa3_1
  - brotlicffi=1.1.0.0=py311h50f4ffc_0
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - certifi=2025.11.12=py311hca03da5_0
  - cffi=2.0.0=py311h73c2a22_1
  - charset-normalizer=3.4.4=py311hca03da5_0
  - comm=0.2.3=pyhe01879c_0
  - debugpy=1.8.16=py311h50f4ffc_1
  - decorator=5.2.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.3=h982b769_0
  - filelock=3.20.0=py311hca03da5_0
  - fsspec=2025.10.0=py311h7eb115d_0
  - gmp=6.3.0=h313beb8_0
  - gmpy2=2.2.1=py311h5c1b81f_0
  - idna=3.11=py311hca03da5_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.1.0=pyh5552912_0
  - ipython=9.7.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=py311hca03da5_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - krb5=1.21.3=h237132a_0
  - libabseil=20240116.2=cxx17_h313beb8_0
  - libcxx=20.1.8=hd7fd590_1
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libexpat=2.7.3=haf25636_0
  - libffi=3.4.4=hca03da5_1
  - libgfortran5=15.2.0=hb654fa1_1
  - libopenblas=0.3.30=hf2bb037_2
  - libprotobuf=4.25.3=h514c7bf_0
  - libsodium=1.0.20=h99b78c6_0
  - libsqlite=3.51.1=h9a5124b_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=20.1.8=he822017_0
  - markupsafe=3.0.2=py311h80987f9_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mpc=1.3.1=h80987f9_0
  - mpfr=4.2.1=h80987f9_0
  - mpmath=1.3.0=py311hca03da5_0
  - ncurses=6.5=hee39554_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.5=py311hca03da5_0
  - numexpr=2.14.1=py311h5fbe615_0
  - openssl=3.6.0=h5503f6c_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py311h3f644e9_1
  - parso=0.8.5=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pip=25.3=pyhc872135_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.0.0=py311haa24f5a_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycparser=2.23=py311hca03da5_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pysocks=1.7.1=py311hca03da5_1
  - python=3.11.11=h89a136b_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.11=8_cp311
  - pytorch=2.3.1=gpu_mps_py311h7b7e308_100
  - pytz=2025.2=py311hca03da5_0
  - pyyaml=6.0.3=py311ha9b3269_0
  - pyzmq=27.1.0=py311h5a8c52c_1
  - readline=8.3=h0b18652_0
  - requests=2.32.5=py311hca03da5_1
  - setuptools=80.9.0=py311hca03da5_0
  - six=1.17.0=pyhe01879c_1
  - sleef=3.5.1=h80987f9_2
  - sqlite=3.51.0=hab6afd1_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - sympy=1.14.0=py311hca03da5_0
  - tk=8.6.15=hcd8a7d5_0
  - tornado=6.5.1=py311h80987f9_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h04d1e81_0
  - urllib3=2.5.0=py311hca03da5_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=py311hca03da5_0
  - xz=5.6.4=h80987f9_1
  - yaml=0.2.5=h1a28f6b_0
  - zeromq=4.3.5=h888dc83_9
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - alembic==1.17.2
      - anndata==0.12.7
      - annotated-types==0.7.0
      - array-api-compat==1.12.0
      - attrs==25.4.0
      - bottle==0.13.4
      - click==8.3.1
      - colorlog==6.10.1
      - contourpy==1.3.3
      - cycler==0.12.1
      - donfig==0.8.1.post1
      - et-xmlfile==2.0.0
      - fonttools==4.61.1
      - frozenlist==1.8.0
      - gitdb==4.0.12
      - gitpython==3.1.46
      - google-crc32c==1.8.0
      - h5py==3.15.1
      - joblib==1.5.3
      - kiwisolver==1.4.9
      - legacy-api-wrap==1.5
      - lightning==2.6.0
      - lightning-utilities==0.15.2
      - llvmlite==0.46.0
      - mako==1.3.10
      - matplotlib==3.10.8
      - methylcdm==0.1.0
      - multidict==6.7.0
      - natsort==8.4.0
      - numba==0.63.1
      - numcodecs==0.16.5
      - numpy==1.26.4
      - openpyxl==3.1.5
      - optuna==4.6.0
      - optuna-dashboard==0.20.0
      - optuna-integration==4.6.0
      - patsy==1.0.2
      - pillow==12.0.0
      - propcache==0.4.1
      - protobuf==6.33.2
      - pyarrow==15.0.2
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pynndescent==0.5.13
      - pyparsing==3.3.1
      - pytorch-lightning==2.6.0
      - scanpy==1.11.5
      - scikit-learn==1.8.0
      - scipy==1.16.3
      - seaborn==0.13.2
      - sentry-sdk==2.48.0
      - session-info2==0.3
      - smmap==5.0.2
      - sqlalchemy==2.0.45
      - statsmodels==0.14.6
      - threadpoolctl==3.6.0
      - torchmetrics==1.8.2
      - tqdm==4.67.1
      - typing-inspection==0.4.2
      - umap-learn==0.5.9.post2
      - wandb==0.23.1
      - warmup-scheduler==0.3
      - yarl==1.22.0
      - zarr==3.1.5
prefix: /Users/sophiali/miniconda3/envs/methylcdm-env
