name: methylcdm-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - pytorch>=2.3
  - pytorch-lightning>=2.6
  - matplotlib
  - seaborn
  - h5py
  - pyyaml
  - optuna
  - wandb
  - pip
  - pip:
      - methylcdm==0.1.0
      - optuna-dashboard
      - optuna-integration
      - lightning
      - lightning-utilities
      - scanpy
      - tqdm
      - torchmetrics
      - numba
      - pyarrow
      - umap-learn
      - zarr
      - warmup-scheduler