[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "MethylCDM"
version = "0.1.0"

[tool.setuptools]
packages = ["MethylCDM"]
package-dir = {"" = "src"}
