# ==============================================================================
# Script:           beta_vae.yaml
# Purpose:          Beta-VAE training configurations
# Author:           Sophia Li
# Affiliation:      CCG Lab, Princess Margaret Cancer Center, UHN, UofT
# Date:             11/14/2025
#
# Notes:            Configurations are inspired by RNA-CDM.
# ==============================================================================

# =====| Optuna Hyperparameter Sweep |==========================================

# Path to the input training data
project_data_dir: data/training/methylation
training_data_dir: data/training/methylation

# Path to the study and experiment save directory
experiment_dir: experiments/beta_vae
checkpoint_dir: models/beta_vae

# Split Data paths
train_adata_path: "data/training/methylation/tcga_train_gene_matrix.h5ad"
val_adata_path: "data/training/methylation/tcga_val_gene_matrix.h5ad"
test_adata_path: "data/training/methylation/tcga_test_gene_matrix.h5ad"

# Input AnnData object dimension (number of genes)
input_dim: 18990

# Device parameters
num_workers: 4

# Model parameters (not included in the sweep yet)
encoder_dims: [6000, 4000]
decoder_dims: [4000, 6000]
max_epochs: 100

# Hyperparameter sweep ranges
batch_size: [32, 256]
latent_dim: [128, 512]
beta: [0.001, 0.1]
lr: [0.0001, 0.01]
