# ==============================================================================
# Script:           methylation_preproc.yaml
# Purpose:          DNA methylation downloading and preprocessing configurations
# Author:           Sophia Li
# Affiliation:      CCG Lab, Princess Margaret Cancer Center, UHN, UofT
# Date:             11/14/2025
#
# Notes:            If paths reference outside the project directory, provide
#                   their absolute paths. Else, if they exist within the project
#                   root, provide only the file or directory name.
# ==============================================================================

# =====| Data Downloading |=====================================================
download:

  # Path to the output data directories; initializes data folder per project
  raw_data_dir: data/raw/methylation
  metadata_dir: data/metadata/methylation

# =====| Data Preprocessing |===================================================
preprocess:

  # Path to the output data directories; initializes data folder per project
  intermediate_data_dir: data/intermediate/methylation
  processed_data_dir: data/processed/methylation

  # Toggles for performing preprocessing
  toggle_sample_filtering: True
  toggle_probe_filtering: True
  toggle_imputation: True

  # Minimum number of missing CpG values to omit a sample (QC)
  max_missing_sample: 0.05

  # Minimum number of missing values to omit a CpG (QC)
  max_missing_probe: 0.05
